# Site settings
title: 聚力班组
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 聚力班组
user_description: 
email: julibanzu@protonmail.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: 首页
    url: /
  - title: 教程
    url: / tutorial
  - title:  标签
    url: /tags
  - title: 关于
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
